services:
  open-webui:
    image: knyl2013/open-webui:latest
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OPENID_PROVIDER_URL=https://accounts.google.com/.well-known/openid-configuration
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - ENABLE_OAUTH_SIGNUP=true
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - open-webui:/app/backend/data
    restart: always
  mcpo-time-server:
    container_name: mcpo-time-server
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.11-slim
        WORKDIR /app
        RUN pip install mcpo uv
        # Use CMD to run the server when the container starts
        CMD ["uvx", "mcpo", "--host", "0.0.0.0", "--port", "8000", "--", "uvx", "mcp-server-time", "--local-timezone=America/New_York"]
    restart: always
  mcpo-fetch-server:
    container_name: mcpo-fetch-server
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.11-slim
        WORKDIR /app
        RUN pip install mcpo uv
        CMD ["uvx", "mcpo", "--host", "0.0.0.0", "--port", "8000", "--", "uvx", "mcp-server-fetch"]
    restart: always
  mcpo-thinking-server:
    container_name: mcpo-thinking-server
    build:
      context: .
      dockerfile_inline: |
        FROM nikolaik/python-nodejs:latest
        WORKDIR /app
        RUN pip install mcpo uv
        CMD ["uvx", "mcpo", "--host", "0.0.0.0", "--port", "8000", "--", "npx", "-y", "server-sequential-thinking"]
    restart: always
volumes:
  open-webui:
    external: true