services:
  open-webui:
    image: knyl2013/open-webui:latest
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OPENID_PROVIDER_URL=https://accounts.google.com/.well-known/openid-configuration
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - ENABLE_OAUTH_SIGNUP=true
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - open-webui:/app/backend/data
    restart: always
  mcp-servers:
    container_name: mcp-servers
    build:
      context: .
      dockerfile_inline: |
        FROM python:3.11-slim
        COPY mcp-config.json mcp-config.json
        RUN pip install mcpo uv
        CMD ["mcpo", "--config", "./mcp-config.json"]
    restart: always
volumes:
  open-webui:
    external: true