services:
  open-webui:
    image: knyl2013/open-webui:latest
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OPENID_PROVIDER_URL=https://accounts.google.com/.well-known/openid-configuration
      - OAUTH_MERGE_ACCOUNTS_BY_EMAIL=true
      - ENABLE_OAUTH_SIGNUP=true
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - open-webui:/app/backend/data
    restart: always
volumes:
  open-webui:
    external: true