name: Build, Push, and Deploy Docker Image

on:
  push:
    branches: [ "my-feature-branch" ]
  workflow_dispatch:

jobs:
  # Job 1: Build and Push the image to Docker Hub
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: knyl2013/open-webui:latest

  # Job 2: Deploy the new image to the server
  deploy:
    # This job will only run if the build-and-push job is successful
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Navigate to the directory where your docker-compose.yml is
            cd /path/to/your/docker-compose/folder 
            
            # Pull the new image
            docker-compose pull
            
            # Restart the container with the new image
            docker-compose up -d
            
            # Optional: Clean up old, unused images to save space
            docker image prune -f